services:
  postgres:
    image: postgres:16
    container_name: cryptoetl-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cryptoetl
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cryptoetl"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
